# Site settings
title: Mixette - Blog
email: support@mixetteapp.com
description: > # this means to ignore newlines until "baseurl:"
  The message is in the mix.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://mixette-web-prod3.elasticbeanstalk.com" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:
twitter_username: MixetteApp
facebook_username: MixetteApp
pintrest_username: mixette0093
instagram_username: MixetteApp

# Build settings
markdown: kramdown
